[mypy]
python_version = 3.13
warn_unused_configs = True
show_error_codes = True
pretty = True
namespace_packages = False

[mypy-fastapi.*]
ignore_missing_imports = True

[mypy-starlette.*]
ignore_missing_imports = True

[mypy-airflow.*]
ignore_missing_imports = True

[mypy-sqlalchemy.*]
ignore_missing_imports = True

[mypy-ldap.*]
ignore_missing_imports = True
